version: '2'
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /mnt/homer:/www/assets # Make sure your local config directory exists
    ports:
      - 8080:8080
    user: 1000:1000 # default
    restart: unless-stopped
 