version: "3.8"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./www:/www/assets
      - homer_config:/www/assets
    ports:
      - "8080:8080"
    user: "1000:1000"
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
    networks:
      - homer_network
    labels:
      - "com.docker.compose.project=homer"
      - "com.docker.compose.service=homer"

volumes:
  homer_config:
    driver: local

networks:
  homer_network:
    driver: bridge
